import { UNDRR } from "./projects.js";

const GAR_INITIATIVE = "GAR";
const GAR_CATEGORY = "GAR2025";
const GAR_STEP = "GAR2025";

export const GAR_LAYERS = [
  {
    id: "MX-9R5H9-I0WZ5-CHUV8",
    key: "water-scarcity-child-nutrition",
    label: "Water scarcity and child nutrition",
    type: "cc",
    desc: "Explores where water scarcity overlaps with poor child nutrition outcomes, highlighting areas where water-related pressures may compound children’s vulnerability.",
    source: "UNDRR, GAR 2025",
    citation: "UNDRR, GAR 2025",
    license: "CC BY 4.1",
    project: UNDRR,
    initiative: GAR_INITIATIVE,
    r2rCategory: GAR_CATEGORY,
    rrStep: GAR_STEP,
  },
  {
    id: "MX-Z7JZA-I9BQC-KKVOT",
    key: "fatalities-gem",
    label: "Human Fatalities Global seismic risk",
    type: "vt",
    geometry: "polygon",
    desc: "Shows the estimated risk of fatalities from earthquakes worldwide, identifying areas where seismic hazards and population exposure create the greatest potential human impacts.",
    source: "UNDRR, GAR 2026",
    citation: "UNDRR, GAR 2026",
    license: "CC BY 4.2",
    project: UNDRR,
    initiative: GAR_INITIATIVE,
    r2rCategory: GAR_CATEGORY,
    rrStep: GAR_STEP,
  },
  {
    id: "MX-TQ2DK-9RHAJ-CRPAN",
    key: "ecolosses-gem",
    label: "Economic Losses Global seismic risk",
    type: "vt",
    geometry: "polygon",
    desc: "Presents the estimated economic losses associated with earthquakes, highlighting countries and areas with the greatest concentration of exposed assets and seismic risk.",
    source: "UNDRR, GAR 2027",
    citation: "UNDRR, GAR 2027",
    license: "CC BY 4.3",
    project: UNDRR,
    initiative: GAR_INITIATIVE,
    r2rCategory: GAR_CATEGORY,
    rrStep: GAR_STEP,
  },
  {
    id: "MX-DN3SY-ZR1E5-5PAB2",
    key: "disasters-idp",
    label: "Disasters and IDP",
    type: "cc",
    desc: "Compares disaster occurrence with the distribution of internally displaced people (IDPs), illustrating where displacement and disaster risk may overlap.",
    source: "UNDRR, GAR 2028",
    citation: "UNDRR, GAR 2028",
    license: "CC BY 4.4",
    project: UNDRR,
    initiative: GAR_INITIATIVE,
    r2rCategory: GAR_CATEGORY,
    rrStep: GAR_STEP,
  },
  {
    id: "MX-5FSR9-Y7LUW-BUCCB",
    key: "sdg-drought",
    label: "SDG15.3.1 and Drought frequency",
    type: "rt",
    desc: "Combines drought frequency with SDG indicator 15.3.1—the proportion of land that is degraded—to identify areas facing both recurrent drought and land degradation.",
    source: "UNDRR, GAR 2029",
    citation: "UNDRR, GAR 2029",
    license: "CC BY 4.5",
    project: UNDRR,
    initiative: GAR_INITIATIVE,
    r2rCategory: GAR_CATEGORY,
    rrStep: GAR_STEP,
  },
];
