import { ECO_DRR } from "./projects.js";

const AWAITING = "disabled-awaiting-data";

const HAZARD_INITIATIVE = "Geographic distribution of hotspots for key hazards and exposed sectors";
const HAZARD_STEP = "UNDERSTAND YOUR HAZARD PROFILE";

export const HAZARD_LAYERS = [
  {
    id: null,
    key: "drought",
    label: "Drought",
    type: "rt",
    desc: "Drought hazard — current conditions.",
    source: "Source to be confirmed.",
    citation: "Source to be confirmed.",
    license: "TBD",
    project: ECO_DRR,
    initiative: HAZARD_INITIATIVE,
    r2rCategory: "Societies",
    rrStep: HAZARD_STEP,
    status: AWAITING,
    note: "Awaiting data — MapX view not yet available.",
  },
  {
    id: null,
    key: "edra-crop-yield-reduction",
    label: "Drought impact on crop yields (EDRA)",
    type: "vt",
    geometry: "polygon",
    desc: "Experimental external source. Average annual crop yield reduction due to drought at NUTS-2 level. Compare barley, maize, and wheat across historical, current, and global-warming scenarios.",
    source: "Copernicus Emergency Management Service — European Drought Risk Atlas",
    sourceUrl: "https://drought.emergency.copernicus.eu/tumbo/edra/explore",
    citation:
      "Rossi, L. et al. (2023), European Drought Risk Atlas, Publications Office of the European Union, EUR 31682 EN, doi:10.2760/608737. Contains modified Copernicus Emergency Management Service information 2026.",
    license: "Copernicus CEMS terms and conditions",
    licenseUrl: "https://drought.emergency.copernicus.eu/terms%26conditions/",
    initiative: "EDRA drought-related crop yield reduction",
    r2rCategory: "Societies",
    rrStep: HAZARD_STEP,
    external: {
      provider: "edra-agriculture",
      defaults: { crop: "WHEAT", scenario: "20" },
    },
    note: "Prototype: fetched from EDRA at runtime and injected into MapX as a temporary GeoJSON view.",
  },
  {
    id: null,
    key: "extreme-heat",
    label: "Extreme Heat",
    type: "rt",
    desc: "Extreme heat hazard.",
    source: "Source to be confirmed.",
    citation: "Source to be confirmed.",
    license: "TBD",
    project: ECO_DRR,
    initiative: HAZARD_INITIATIVE,
    r2rCategory: "Societies",
    rrStep: HAZARD_STEP,
    status: AWAITING,
    note: "Awaiting data — MapX view not yet available.",
  },
  {
    id: null,
    key: "river-flooding",
    label: "River Flooding",
    type: "rt",
    desc: "Flood hazard from the GAR model.",
    source:
      "GAR/PREVIEW platform (UNEP/GRID-Geneva) via MapX. Underlying data: WRI Aqueduct Floods; JRC Global River Flood Hazard Maps.",
    sourceUrl: "https://unepgrid.ch/en/activity/1BDE1705",
    citation:
      "Ward, P.J. et al. (2020): Aqueduct Floods Methodology. WRI Technical Note, Washington D.C. / Baugh, C. et al. (2024): Global river flood hazard maps. JRC. doi:10.2905/jrc-floods-floodmapgl.",
    license: "CC BY 4.0",
    legendNote: "“Absent” in the source legend means that no data is reported for that location.",
    project: ECO_DRR,
    initiative: HAZARD_INITIATIVE,
    r2rCategory: "Societies",
    rrStep: HAZARD_STEP,
    sources: [
      {
        id: "MX-V07LO-829XA-4BIZ8",
        label: "Depth",
        desc: "Flood depth in mm, 25yr return period.",
        legend: [
          { color: "#f7fbff", label: "<= 10 mm" },
          { color: "#d2e3f3", label: "50 mm" },
          { color: "#9fcae1", label: "100 mm" },
          { color: "#6baed6", label: "200 mm" },
          { color: "#3182bd", label: "500 mm" },
          { color: "#1c6cb1", label: "1000 mm" },
          { color: "#0b4d94", label: "2000 mm" },
          { color: "#08306b", label: "5000 mm" },
          { color: "#041e42", label: "> 5000 mm" },
        ],
      },
      {
        id: "MX-21A2A-BED99-D8D78",
        label: "Frequency",
        desc: "Annual frequency of river floods, 25-1000yr return period.",
      },
      {
        id: "MX-4918F-8A0E5-AF76B",
        label: "Exposure",
        desc: "Physical exposure to river flooding (source-defined annual estimate).",
      },
    ],
    widget: { type: "sub-tabs", label: "Metric" },
  },
  {
    id: null,
    key: "earthquake-pga",
    label: "Earthquake PGA",
    type: "rt",
    desc: "Peak Ground Acceleration from the GEM Global Seismic Hazard Map.",
    source: "Global Earthquake Model (GEM) Foundation.",
    sourceUrl: "https://www.globalquakemodel.org/gem",
    citation:
      "Pagani, M. et al. (2018): Global Earthquake Model (GEM) Seismic Hazard Map. Earthquake Spectra, 34(4): 1281–1296. doi:10.1193/160117EQS316M.",
    license: "CC BY-NC-SA 4.0",
    project: ECO_DRR,
    initiative: HAZARD_INITIATIVE,
    r2rCategory: "Societies",
    rrStep: HAZARD_STEP,
    sources: [
      { id: "MX-J3YTW-RUQN3-40P87", label: "250 yr" },
      { id: "MX-4XSGY-9URYF-WMICZ", label: "475 yr" },
      { id: "MX-KE2UX-GL8CM-IZSIA", label: "975 yr" },
      { id: "MX-SFF5U-3O2XL-SAIL9", label: "1500 yr" },
      { id: "MX-MWJ8Z-JYVYX-N9T0T", label: "2475 yr" },
    ],
    widget: { type: "stepped-slider", label: "Return period" },
  },
  {
    id: "MX-YLZJG-JAIID-V27X5",
    key: "earthquakes-live",
    label: "Earthquakes (live)",
    type: "cc",
    geometry: "point",
    desc: "USGS Mag >= 5.5, past 30 days. Updated every 15 min.",
    source: "USGS Earthquake Hazards Program.",
    sourceUrl: "https://earthquake.usgs.gov/earthquakes/feed/",
    citation:
      "USGS Earthquake Hazards Program. Advanced National Seismic System Comprehensive Earthquake Catalog (ComCat). earthquake.usgs.gov/earthquakes/feed/",
    license: "Public Domain (U.S. Government)",
    project: ECO_DRR,
    initiative: HAZARD_INITIATIVE,
    r2rCategory: "Societies",
    rrStep: HAZARD_STEP,
  },
  {
    id: "MX-8C214-22C3A-82165",
    key: "cyclone-surge",
    label: "Storm: Tropical Cyclone Surge",
    type: "rt",
    desc: "Physical exposure to storm surge generated by tropical cyclones (source-defined annual estimate).",
    source: "GAR/PREVIEW platform (UNEP/GRID-Geneva) via MapX.",
    sourceUrl: "https://unepgrid.ch/en/activity/1BDE1705",
    citation:
      "GAR/PREVIEW Platform, UNEP/GRID-Geneva. Based on Ward, P.J. et al. (2020): Aqueduct Floods Methodology. WRI.",
    license: "CC BY 4.0",
    legendNote: "“Absent” in the source legend means that no data is reported for that location.",
    project: ECO_DRR,
    initiative: HAZARD_INITIATIVE,
    r2rCategory: "Societies",
    rrStep: HAZARD_STEP,
  },
  {
    id: null,
    key: "tropical-cyclones",
    label: "Storm: Tropical Cyclone Wind",
    type: "rt",
    desc: "Tropical-cyclone wind speed and physical exposure.",
    source: "STORM Tropical Cyclone dataset (Bloemendaal et al.); IRIS Imperial College Storm Model.",
    sourceUrl: "https://www.nature.com/articles/s41597-020-0381-2",
    citation:
      "Bloemendaal, N. et al. (2020): Generation of a global synthetic tropical cyclone hazard dataset using STORM. Scientific Data, 7: 40. doi:10.1038/s41597-020-0381-2.",
    license: "CC0 1.0 (STORM) / CC BY 4.0 (IRIS)",
    legendNote: "“Absent” in the source legend means that no data is reported for that location.",
    project: ECO_DRR,
    initiative: HAZARD_INITIATIVE,
    r2rCategory: "Societies",
    rrStep: HAZARD_STEP,
    sources: [
      {
        id: "MX-E180C-5B012-AFC77",
        label: "Wind frequency",
        desc: "Cyclone wind speed probabilities (STORM dataset).",
      },
      {
        id: "MX-10AE5-746D1-76777",
        label: "Wind exposure",
        desc: "Physical exposure to tropical-cyclone winds (source-defined annual estimate).",
      },
    ],
    widget: { type: "sub-tabs", label: "Metric" },
  },
  {
    id: null,
    key: "landslides",
    label: "Landslides",
    type: "rt",
    desc: "Earthquake and precipitation triggered landslides.",
    source: "GAR/PREVIEW platform (UNEP/GRID-Geneva) via MapX.",
    sourceUrl: "https://unepgrid.ch/en/activity/1BDE1705",
    citation: "GAR/PREVIEW Platform, UNEP/GRID-Geneva.",
    license: "UNEP",
    legendNote: "“Absent” in the source legend means that no data is reported for that location.",
    project: ECO_DRR,
    initiative: HAZARD_INITIATIVE,
    r2rCategory: "Societies",
    rrStep: HAZARD_STEP,
    sources: [
      {
        id: "MX-04E66-2E550-81068",
        label: "Exposure",
        desc: "Physical exposure to landslides (source-defined annual estimate).",
      },
      {
        id: "MX-05247-89997-66A64",
        label: "Frequency",
        desc: "Annual frequency of landslides.",
      },
    ],
    widget: { type: "sub-tabs", label: "Metric" },
  },
  {
    id: null,
    key: "tsunamis",
    label: "Tsunamis",
    type: "rt",
    desc: "Tsunami exposure and frequency.",
    source: "GAR/PREVIEW platform (UNEP/GRID-Geneva) via MapX.",
    sourceUrl: "https://unepgrid.ch/en/activity/1BDE1705",
    citation: "GAR/PREVIEW Platform, UNEP/GRID-Geneva.",
    license: "UNEP",
    legendNote: "“Absent” in the source legend means that no data is reported for that location.",
    project: ECO_DRR,
    initiative: HAZARD_INITIATIVE,
    r2rCategory: "Societies",
    rrStep: HAZARD_STEP,
    sources: [
      {
        id: "MX-F0DEE-12D97-6447B",
        label: "Exposure",
        desc: "Physical exposure to tsunamis (source-defined annual estimate).",
      },
      {
        id: "MX-D7314-A5044-83377",
        label: "Frequency",
        desc: "Annual frequency of tsunamis.",
      },
    ],
    widget: { type: "sub-tabs", label: "Metric" },
  },
  {
    id: null,
    key: "wildfire",
    label: "Wildfire",
    type: "rt",
    desc: "Wildfire hazard.",
    source: "Source to be confirmed.",
    citation: "Source to be confirmed.",
    license: "TBD",
    project: ECO_DRR,
    initiative: HAZARD_INITIATIVE,
    r2rCategory: "Societies",
    rrStep: HAZARD_STEP,
    status: AWAITING,
    note: "Awaiting data — MapX view not yet available.",
  },
  {
    id: null,
    key: "impacts-multiple-shocks",
    label: "Impacts of Multiple Shocks",
    type: "vt",
    desc: "Compound and cascading impacts from multiple concurrent hazard shocks.",
    source: "Source to be confirmed.",
    citation: "Source to be confirmed.",
    license: "TBD",
    project: ECO_DRR,
    initiative: "Impacts of multiple shocks",
    r2rCategory: "Societies",
    rrStep: HAZARD_STEP,
    status: AWAITING,
    note: "Awaiting data — MapX view not yet available.",
  },
];
