import { ECO_DRR } from "./projects.js";

const AWAITING = "disabled-awaiting-data";
const SOURCE_TBC = "Source to be confirmed.";
const CITATION_TBC = "Source to be confirmed.";
const LICENSE_TBC = "TBD";
const NOTE_PENDING = "Awaiting data — MapX view not yet available.";

const STEP_UNDERSTAND = "UNDERSTAND YOUR HAZARD PROFILE";
const STEP_LINK = "LINK TO YOUR ECONOMIC AND SOCIAL EXPOSURE";
const STEP_PRIORITIZE = "PRIORITIZE CURRENT AND FUTURE INVESTMENT";

export const RESILIENCE_LAYERS = [
  {
    id: null,
    key: "change-fiscal-gap",
    label: "Change in Fiscal Gap",
    type: "vt",
    geometry: "point",
    desc: "Change in fiscal gap with and without financial support under resilience interventions.",
    source: SOURCE_TBC,
    citation: CITATION_TBC,
    license: LICENSE_TBC,
    project: ECO_DRR,
    initiative: "Change in fiscal gap with and without resilience measures",
    r2rCategory: "Economy",
    rrStep: STEP_LINK,
    sources: [
      {
        id: "MX-WOHMT-WYKWK-X25K9",
        label: "With support",
        desc: "Change in fiscal gap with financial support.",
      },
      {
        id: "MX-5GL7W-40NYZ-T1IX1",
        label: "Without support",
        desc: "Change in fiscal gap without financial support.",
      },
    ],
    widget: { type: "sub-tabs", label: "Scenario" },
  },
  {
    id: null,
    key: "recovery-consumption",
    label: "Recovery consumption",
    type: "vt",
    geometry: "point",
    desc: "Post-disaster well-being, consumption recovery and asset ownership for the poorest households with and without resilient investment",
    source: SOURCE_TBC,
    citation: CITATION_TBC,
    license: LICENSE_TBC,
    project: ECO_DRR,
    initiative: "Recovery of household consumption and asset ownership resilience after an extreme event",
    r2rCategory: "Societies",
    rrStep: STEP_LINK,
    status: AWAITING,
    note: NOTE_PENDING,
  },
  {
    id: null,
    key: "adaptation",
    label: "Adaptation in Infrastructure losses",
    type: "vt",
    geometry: "point",
    desc: "Spatial distribution of adaptation measures and resilience interventions.",
    source: SOURCE_TBC,
    citation: CITATION_TBC,
    license: LICENSE_TBC,
    project: ECO_DRR,
    initiative: "Adaptation benefit in reduced losses to infrastructure (under 2.6 and 8.5 RCP?)",
    r2rCategory: "Societies",
    rrStep: STEP_LINK,
    status: AWAITING,
    note: NOTE_PENDING,
  },
  // — Stubs from inventory (no MapX view yet) —
  {
    id: "MX-SL3SM-AR11B-4LQ8T",
    key: "early-warning-coverage",
    label: "Early Warning Coverage",
    type: "vt",
    desc: "Number of hazards covered by an early warning system and number of Admin 2 risk models.",
    source: "UNDRR",
    citation: "Sendai Framework Monitor, UNDRR",
    license: "Creative Commons Attribution 4.0 International (CC BY 4.0)",
    project: ECO_DRR,
    initiative: "# hazards covered by an early warning system and # of Admin 2 risk models",
    r2rCategory: "Societies",
    rrStep: STEP_UNDERSTAND,
    status: AWAITING,
    note: NOTE_PENDING,
  },
  {
    id: null,
    key: "economic-impacts-reduction",
    label: "Reduction in Economic Impacts of Multiple Shocks",
    type: "vt",
    desc: "Reduction in economic impacts of multiple shocks with resilient investment.",
    source: SOURCE_TBC,
    citation: CITATION_TBC,
    license: LICENSE_TBC,
    project: ECO_DRR,
    initiative: "Reduction in economic impacts of multiple shocks with resilient investement",
    r2rCategory: "Societies",
    rrStep: STEP_UNDERSTAND,
    status: AWAITING,
    note: NOTE_PENDING,
  },
  {
    id: null,
    key: "life-years-adaptation-benefit",
    label: "Reduction in life years lost",
    type: "vt",
    desc: "Adaptation benefit in relation to life years lost from disasters.",
    source: SOURCE_TBC,
    citation: CITATION_TBC,
    license: LICENSE_TBC,
    project: ECO_DRR,
    initiative: "Adaptation benefit of adaptation to life years lost",
    r2rCategory: "Societies",
    rrStep: STEP_LINK,
    status: AWAITING,
    note: NOTE_PENDING,
  },
  {
    id: null,
    key: "recovery-utilities",
    label: "Recovery Time Utilities",
    type: "vt",
    desc: "Recovery time of utilities after a major shock; restoration time for public assets.",
    source: SOURCE_TBC,
    citation: CITATION_TBC,
    license: LICENSE_TBC,
    project: ECO_DRR,
    initiative:
      "Recovery time of utilities after a major shock, recovery time for restoration of public assets",
    r2rCategory: "Economy",
    rrStep: STEP_LINK,
    status: AWAITING,
    note: NOTE_PENDING,
  },
  {
    id: null,
    key: "agricultural-losses-reduction",
    label: "Reduction in Agricultural Losses",
    type: "vt",
    desc: "Reduction in agricultural losses with and without resilience measures under RCP 2.6 and 8.5 scenarios.",
    source: SOURCE_TBC,
    citation: CITATION_TBC,
    license: LICENSE_TBC,
    project: ECO_DRR,
    initiative:
      "Reduction in agricultural losses with and without resilience measures under 2.6 and 8.5 scenarios",
    r2rCategory: "Environment",
    rrStep: STEP_LINK,
    status: AWAITING,
    note: NOTE_PENDING,
  },
  {
    id: null,
    key: "food-price-impact",
    label: "Food Price Impact of Climate Change",
    type: "vt",
    desc: "Impact of climate change and resilience building on food prices (FAO elasticity calculations 2026–2027).",
    source: SOURCE_TBC,
    citation: CITATION_TBC,
    license: LICENSE_TBC,
    project: ECO_DRR,
    initiative:
      "Impact of climate change and resilience building on food prices (FAO elastacity calculations 2026-2027)",
    r2rCategory: "Environment",
    rrStep: STEP_LINK,
    status: AWAITING,
    note: NOTE_PENDING,
  },
  {
    id: null,
    key: "resilient-housing-benefit",
    label: "Adaptation Benefit of Resilient Housing",
    type: "vt",
    desc: "Adaptation benefit of increase in resilient housing including insurability, house price, mortgage and insurance affordability.",
    source: SOURCE_TBC,
    citation: CITATION_TBC,
    license: LICENSE_TBC,
    project: ECO_DRR,
    initiative:
      "Adaptation benefit of increase in resilient housing / Insurability/ house price/mortgage/ insurance affordability/ needs some work, may need two types",
    r2rCategory: "Societies",
    rrStep: STEP_LINK,
    status: AWAITING,
    note: NOTE_PENDING,
  },
  {
    id: null,
    key: "ecosystem-investment-benefit",
    label: "Adaptation Benefit via Ecosystem Investment",
    type: "vt",
    desc: "Adaptation benefit in reduced losses through ecosystem investment under RCP 2.6 and 8.5 scenarios.",
    source: SOURCE_TBC,
    citation: CITATION_TBC,
    license: LICENSE_TBC,
    project: ECO_DRR,
    initiative: "Adaptation benefit in reduced losses through ecosystem investment (under 2.6 and 8.5 RCP?)",
    r2rCategory: "Environment",
    rrStep: STEP_LINK,
    status: AWAITING,
    note: NOTE_PENDING,
  },
  {
    id: null,
    key: "adaptation-benefit-gdp",
    label: "Adaptation Benefit to GDP Growth",
    type: "vt",
    desc: "Adaptation benefit to GDP growth and benefit to poverty headcount without a major shock.",
    source: SOURCE_TBC,
    citation: CITATION_TBC,
    license: LICENSE_TBC,
    project: ECO_DRR,
    initiative: "Adaptation benefit to GDP growth/ benefit to poverty headcount (without major shock)",
    r2rCategory: "Economy",
    rrStep: STEP_LINK,
    status: AWAITING,
    note: NOTE_PENDING,
  },
  {
    id: null,
    key: "resilience-benefit-gdp",
    label: "Resilience Benefit to GDP Growth",
    type: "vt",
    desc: "Resilience benefit to GDP growth with and without investment in case of a 1:100 year event.",
    source: SOURCE_TBC,
    citation: CITATION_TBC,
    license: LICENSE_TBC,
    project: ECO_DRR,
    initiative: "Resilience benefit to GDP growth with and without investment in case of a 1:100 year event",
    r2rCategory: "Economy",
    rrStep: STEP_LINK,
    status: AWAITING,
    note: NOTE_PENDING,
  },
  {
    id: null,
    key: "supply-chain-damage-reduction",
    label: "Reduction in Supply Chain Damage",
    type: "vt",
    desc: "Reduction in supply chain damage with adaptation investment.",
    source: SOURCE_TBC,
    citation: CITATION_TBC,
    license: LICENSE_TBC,
    project: ECO_DRR,
    initiative: "Reduction in supply chain damage with adaptation investment",
    r2rCategory: "Economy",
    rrStep: STEP_LINK,
    status: AWAITING,
    note: NOTE_PENDING,
  },
  {
    id: null,
    key: "bank-solvency-resilience",
    label: "Bank Solvency with Resilience Measures",
    type: "vt",
    desc: "Bank solvency to a PML event with and without resilience measures.",
    source: SOURCE_TBC,
    citation: CITATION_TBC,
    license: LICENSE_TBC,
    project: ECO_DRR,
    initiative: "Bank solvency to a PML event with and without resilience measures",
    r2rCategory: "Economy",
    rrStep: STEP_LINK,
    status: AWAITING,
    note: NOTE_PENDING,
  },
  {
    id: null,
    key: "sovereign-debt-pml",
    label: "Sovereign Debt Change (PML Event)",
    type: "vt",
    desc: "Sovereign debt change due to a PML event (stress test).",
    source: SOURCE_TBC,
    citation: CITATION_TBC,
    license: LICENSE_TBC,
    project: ECO_DRR,
    initiative: "Sovereign debt change due to a PML event (Stress test)",
    r2rCategory: "Economy",
    rrStep: STEP_LINK,
    status: AWAITING,
    note: NOTE_PENDING,
  },
  {
    id: null,
    key: "drr-future-spending",
    label: "Future DRR / Resilience Spending",
    type: "vt",
    desc: "Future planned spending on DRR and resilience in relation to AAL/PML.",
    source: SOURCE_TBC,
    citation: CITATION_TBC,
    license: LICENSE_TBC,
    project: ECO_DRR,
    initiative: "Future planned spending on DRR / resilience in relation to AAL/ PML",
    r2rCategory: "Societies",
    rrStep: STEP_PRIORITIZE,
    status: AWAITING,
    note: NOTE_PENDING,
  },
  {
    id: null,
    key: "emergency-funding",
    label: "Emergency Funding Requirement",
    type: "vt",
    desc: "Percentage of emergency funding required with and without a reserve in a PML event.",
    source: SOURCE_TBC,
    citation: CITATION_TBC,
    license: LICENSE_TBC,
    project: ECO_DRR,
    initiative: "% of emergency funding required with and without a reserve in a PML event",
    r2rCategory: "Economy",
    rrStep: STEP_PRIORITIZE,
    status: AWAITING,
    note: NOTE_PENDING,
  },
];
