import { ECO_DRR } from "./projects.js";

const AWAITING = "disabled-awaiting-data";
const SOURCE_TBC = "Source to be confirmed.";
const CITATION_TBC = "Source to be confirmed.";
const LICENSE_TBC = "TBD";
const NOTE_PENDING = "Awaiting data — MapX view not yet available.";

const STEP_LINK = "LINK TO YOUR ECONOMIC AND SOCIAL EXPOSURE";
const STEP_PRIORITIZE = "PRIORITIZE CURRENT AND FUTURE INVESTMENT";
const STEP_CONSIDER = "CONSIDER POTENTIAL RESILIENCE OPTIONS";

const HAZARD_SOURCES = [
  { id: null, label: "Earthquake", desc: "Earthquake hazard." },
  { id: null, label: "Landslides", desc: "Landslide hazard." },
  { id: null, label: "Tropical Cyclones", desc: "Tropical cyclone hazard." },
  { id: null, label: "Floods", desc: "Flood hazard." },
  { id: null, label: "Tsunamis", desc: "Tsunami hazard." },
];

export const RISK_LAYERS = [
  {
    id: null,
    key: "recovery-speed",
    label: "Recovery Speed",
    type: "vt",
    geometry: "point",
    desc: "Recovery speed of consumption levels after a 1:100 event, by hazard type.",
    source: SOURCE_TBC,
    citation: CITATION_TBC,
    license: LICENSE_TBC,
    project: ECO_DRR,
    initiative: "Recovery speed top/bottom quintile for an AAL/ PML",
    r2rCategory: "Societies",
    rrStep: STEP_LINK,
    status: AWAITING,
    note: NOTE_PENDING,
    sources: [
      { id: null, label: "Earthquake", desc: "Recovery speed after a 1:100 earthquake event." },
      { id: null, label: "Flood", desc: "Recovery speed after a 1:100 flood event." },
      { id: null, label: "Storm", desc: "Recovery speed after a 1:100 storm event." },
      { id: null, label: "Tsunami", desc: "Recovery speed after a 1:100 tsunami event." },
    ],
    widget: { type: "sub-tabs", label: "Hazard" },
  },
  {
    id: null,
    key: "aal-public",
    label: "AAL — Public Assets",
    type: "vt",
    geometry: "point",
    desc: "Average annual loss for public assets under current and future climate scenarios.",
    source: SOURCE_TBC,
    citation: CITATION_TBC,
    license: LICENSE_TBC,
    project: ECO_DRR,
    initiative: "AAL to public infrastructure",
    r2rCategory: "Societies",
    rrStep: STEP_LINK,
    sources: [
      { id: "MX-443WM-S89FY-2ANCD", label: "Current", desc: "AAL for public assets under current climate." },
      { id: "MX-6HW4M-X4PAM-WH46T", label: "RCP 2.6", desc: "AAL for public assets under RCP 2.6." },
      { id: "MX-QLZI0-AXK6X-8OAN7", label: "RCP 8.5", desc: "AAL for public assets under RCP 8.5." },
    ],
    widget: { type: "stepped-slider", label: "Climate scenario" },
  },
  {
    id: null,
    key: "edra-crop-yield-reduction",
    label: "Drought impact on crop yields (EDRA)",
    type: "vt",
    geometry: "polygon",
    desc: "Experimental external source. Average annual crop yield reduction due to drought at NUTS-2 level. Compare barley, maize, and wheat across historical, current, and global-warming scenarios.",
    source: "Copernicus Emergency Management Service — European Drought Risk Atlas",
    sourceUrl: "https://drought.emergency.copernicus.eu/tumbo/edra/explore",
    citation:
      "Rossi, L. et al. (2023), European Drought Risk Atlas, Publications Office of the European Union, EUR 31682 EN, doi:10.2760/608737. Contains modified Copernicus Emergency Management Service information 2026.",
    license: "Copernicus CEMS terms and conditions",
    licenseUrl: "https://drought.emergency.copernicus.eu/terms%26conditions/",
    initiative: "EDRA drought-related crop yield reduction",
    r2rCategory: "Environment",
    rrStep: STEP_LINK,
    external: {
      provider: "edra-agriculture",
      defaults: { crop: "WHEAT", scenario: "20" },
    },
    note: "Prototype: fetched from EDRA at runtime and injected into MapX as a temporary GeoJSON view.",
  },
  {
    id: null,
    key: "aal-crops",
    label: "AAL — Crops",
    type: "vt",
    geometry: "point",
    desc: "Average annual loss for crops.",
    source: SOURCE_TBC,
    citation: CITATION_TBC,
    license: LICENSE_TBC,
    project: ECO_DRR,
    initiative: "AAL crops",
    r2rCategory: "Environment",
    rrStep: STEP_LINK,
    status: AWAITING,
    note: NOTE_PENDING,
  },
  {
    id: null,
    key: "pml-crops",
    label: "PML — Crops",
    type: "vt",
    geometry: "point",
    desc: "Probable maximum loss for crops.",
    source: SOURCE_TBC,
    citation: CITATION_TBC,
    license: LICENSE_TBC,
    project: ECO_DRR,
    initiative: "PML crops",
    r2rCategory: "Environment",
    rrStep: STEP_LINK,
    status: AWAITING,
    note: NOTE_PENDING,
  },
  {
    id: null,
    key: "aal-pml-housing",
    label: "AAL / PML — Housing",
    type: "vt",
    geometry: "point",
    desc: "Average annual loss and probable maximum loss for housing stock under current and future climate scenarios.",
    source: SOURCE_TBC,
    citation: CITATION_TBC,
    license: LICENSE_TBC,
    project: ECO_DRR,
    initiative: "AAL/PML housing",
    r2rCategory: "Societies",
    rrStep: STEP_LINK,
    sources: [
      { id: "MX-YP5S0-VBMJK-R7IMX", label: "AAL Current", desc: "AAL for housing under current climate." },
      { id: "MX-MKE3F-AONM0-27UM0", label: "AAL RCP 2.6", desc: "AAL for housing under RCP 2.6." },
      { id: "MX-O1L8F-IKWHZ-VZTO7", label: "AAL RCP 8.5", desc: "AAL for housing under RCP 8.5." },
      { id: "MX-ZA12C-TU5AH-L9K7P", label: "PML Current", desc: "PML for housing under current climate." },
      { id: "MX-XY8R2-9T29I-7235T", label: "PML RCP 2.6", desc: "PML for housing under RCP 2.6." },
      { id: "MX-VWYGB-7A6CV-QC1UG", label: "PML RCP 8.5", desc: "PML for housing under RCP 8.5." },
    ],
    widget: { type: "sub-tabs", label: "Metric / Scenario" },
  },
  {
    id: null,
    key: "ecosystem-loss",
    label: "Ecosystem Loss",
    type: "vt",
    geometry: "point",
    desc: "Ecosystem loss resulting from disaster events.",
    source: SOURCE_TBC,
    citation: CITATION_TBC,
    license: LICENSE_TBC,
    project: ECO_DRR,
    initiative: "Economic loss to ecosystem failure under current conditions",
    r2rCategory: "Environment",
    rrStep: STEP_LINK,
    status: AWAITING,
    note: NOTE_PENDING,
  },
  {
    id: null,
    key: "aal-to-gdp-2025",
    label: "AAL to GDP (2025)",
    type: "vt",
    geometry: "point",
    desc: "Average annual loss as a share of GDP (2025 baseline), by hazard.",
    source: SOURCE_TBC,
    citation: CITATION_TBC,
    license: LICENSE_TBC,
    project: ECO_DRR,
    initiative: "AAL to GDP now and 2050",
    r2rCategory: "Economy",
    rrStep: STEP_LINK,
    sources: [
      { id: "MX-9NADN-CB8JT-WC1OD", label: "Earthquake", desc: "AAL to GDP 2025 — earthquake." },
      { id: "MX-Y0QE0-24K69-FKLY4", label: "Landslides", desc: "AAL to GDP 2025 — landslides." },
      {
        id: "MX-1IW5U-0WB6E-23TWY",
        label: "Tropical Cyclones",
        desc: "AAL to GDP 2025 — tropical cyclones.",
      },
      { id: "MX-YYCOH-BJR17-AI5DC", label: "Floods", desc: "AAL to GDP 2025 — floods." },
      { id: "MX-GWI29-SUI19-JI9NK", label: "Tsunamis", desc: "AAL to GDP 2025 — tsunamis." },
    ],
    widget: { type: "sub-tabs", label: "Hazard" },
  },
  {
    id: null,
    key: "pml-to-gdp-2025",
    label: "PML to GDP (2025)",
    type: "vt",
    geometry: "point",
    desc: "Probable maximum loss as a share of GDP (2025 baseline), by hazard.",
    source: SOURCE_TBC,
    citation: CITATION_TBC,
    license: LICENSE_TBC,
    project: ECO_DRR,
    initiative: "PML to GDP now and in 2050",
    r2rCategory: "Economy",
    rrStep: STEP_LINK,
    sources: [
      { id: "MX-D7PMU-PL88W-UYF2D", label: "Earthquake", desc: "PML to GDP 2025 — earthquake." },
      { id: "MX-AXEIH-GM2KV-TGOII", label: "Landslides", desc: "PML to GDP 2025 — landslides." },
      {
        id: "MX-V0I12-3KA70-ZVMX9",
        label: "Tropical Cyclones",
        desc: "PML to GDP 2025 — tropical cyclones.",
      },
      { id: "MX-2C1U4-W0QF9-OQ7EO", label: "Floods", desc: "PML to GDP 2025 — floods." },
      { id: "MX-C7MNL-TEXT7-TN001", label: "Tsunamis", desc: "PML to GDP 2025 — tsunamis." },
    ],
    widget: { type: "sub-tabs", label: "Hazard" },
  },
  {
    id: null,
    key: "aal-to-gdp-2050",
    label: "AAL to GDP (2050)",
    type: "vt",
    geometry: "point",
    desc: "Average annual loss as a share of GDP (2050 projection), by hazard.",
    source: SOURCE_TBC,
    citation: CITATION_TBC,
    license: LICENSE_TBC,
    project: ECO_DRR,
    initiative: "AAL to GDP now and 2050",
    r2rCategory: "Economy",
    rrStep: STEP_LINK,
    status: AWAITING,
    note: NOTE_PENDING,
    sources: HAZARD_SOURCES.map((s) => ({ ...s, desc: `AAL to GDP 2050 — ${s.label.toLowerCase()}.` })),
    widget: { type: "sub-tabs", label: "Hazard" },
  },
  {
    id: null,
    key: "pml-to-gdp-2050",
    label: "PML to GDP (2050)",
    type: "vt",
    geometry: "point",
    desc: "Probable maximum loss as a share of GDP (2050 projection), by hazard.",
    source: SOURCE_TBC,
    citation: CITATION_TBC,
    license: LICENSE_TBC,
    project: ECO_DRR,
    initiative: "PML to GDP now and in 2050",
    r2rCategory: "Economy",
    rrStep: STEP_LINK,
    status: AWAITING,
    note: NOTE_PENDING,
    sources: HAZARD_SOURCES.map((s) => ({ ...s, desc: `PML to GDP 2050 — ${s.label.toLowerCase()}.` })),
    widget: { type: "sub-tabs", label: "Hazard" },
  },
  {
    id: null,
    key: "current-fiscal-gap",
    label: "Current Fiscal Gap",
    type: "vt",
    geometry: "point",
    desc: "Current fiscal gap (cost of uninsured disaster losses) by hazard.",
    source: SOURCE_TBC,
    citation: CITATION_TBC,
    license: LICENSE_TBC,
    project: ECO_DRR,
    initiative: "Current fiscal gap",
    r2rCategory: "Economy",
    rrStep: STEP_LINK,
    sources: [
      { id: "MX-X144T-FVH4D-CNILH", label: "Floods", desc: "Current fiscal gap — floods." },
      { id: "MX-6R1HD-1QCSB-CDRCP", label: "Landslides", desc: "Current fiscal gap — landslides." },
      {
        id: "MX-VPWOT-F3J3E-N5CPW",
        label: "Tropical Cyclones",
        desc: "Current fiscal gap — tropical cyclones.",
      },
      { id: "MX-HH3SN-J2JQY-ZKSZV", label: "Earthquake", desc: "Current fiscal gap — earthquake." },
      { id: "MX-I91L8-9WESU-ZXA05", label: "Tsunamis", desc: "Current fiscal gap — tsunamis." },
    ],
    widget: { type: "sub-tabs", label: "Hazard" },
  },
  {
    id: null,
    key: "cost-supply-chain-disruption",
    label: "Cost of Supply Chain Disruption",
    type: "vt",
    geometry: "point",
    desc: "Economic cost of disaster-induced supply chain disruption.",
    source: SOURCE_TBC,
    citation: CITATION_TBC,
    license: LICENSE_TBC,
    project: ECO_DRR,
    initiative: "Cost of supply chain disruption",
    r2rCategory: "Economy",
    rrStep: STEP_LINK,
    status: AWAITING,
    note: NOTE_PENDING,
  },
  {
    id: null,
    key: "bank-solvency-capital-adequacy",
    label: "Bank Solvency / Capital Adequacy",
    type: "vt",
    geometry: "point",
    desc: "Bank solvency in an AAL year and capital adequacy indicators.",
    source: SOURCE_TBC,
    citation: CITATION_TBC,
    license: LICENSE_TBC,
    project: ECO_DRR,
    initiative: "Bank solvency in an AAL year / capital adequacy",
    r2rCategory: "Economy",
    rrStep: STEP_LINK,
    status: AWAITING,
    note: NOTE_PENDING,
  },
  {
    id: null,
    key: "sovereign-debt-stress-test",
    label: "Sovereign Debt Stress Test",
    type: "vt",
    geometry: "point",
    desc: "Sovereign debt due to an AAL event (stress test).",
    source: SOURCE_TBC,
    citation: CITATION_TBC,
    license: LICENSE_TBC,
    project: ECO_DRR,
    initiative: "Sovereign debt due to AAL event (Stress test)",
    r2rCategory: "Economy",
    rrStep: STEP_LINK,
    status: AWAITING,
    note: NOTE_PENDING,
  },
  {
    id: null,
    key: "drr-financing-per-gdp",
    label: "DRR / Resilience Financing (% of GDP)",
    type: "vt",
    geometry: "point",
    desc: "Percentage of DRR and resilience financing as a share of GDP.",
    source: SOURCE_TBC,
    citation: CITATION_TBC,
    license: LICENSE_TBC,
    project: ECO_DRR,
    initiative: "Percentage of DRR/ resilience financing per GDP",
    r2rCategory: "Economy",
    rrStep: STEP_PRIORITIZE,
    status: AWAITING,
    note: NOTE_PENDING,
  },
  {
    id: null,
    key: "humanitarian-vs-prevention-expenditure",
    label: "Humanitarian vs. Prevention Expenditure",
    type: "vt",
    geometry: "point",
    desc: "Average expenditure on humanitarian relief compared to anticipatory action and prevention.",
    source: SOURCE_TBC,
    citation: CITATION_TBC,
    license: LICENSE_TBC,
    project: ECO_DRR,
    initiative: "Average expenditure on humanitarian relief as compared to AA/ prevention",
    r2rCategory: "Economy",
    rrStep: STEP_PRIORITIZE,
    status: AWAITING,
    note: NOTE_PENDING,
  },
  {
    id: null,
    key: "layered-financing-matrix",
    label: "Layered Financing Matrix",
    type: "vt",
    desc: "Matrix of potential project types to accelerate resilience based on a layered financing approach.",
    source: SOURCE_TBC,
    citation: CITATION_TBC,
    license: LICENSE_TBC,
    project: ECO_DRR,
    initiative:
      "Based on a layered financing approach, matrix of potential project types that could be explored to accelerate resilience",
    r2rCategory: "Economy",
    rrStep: STEP_CONSIDER,
    status: AWAITING,
    note: NOTE_PENDING,
  },
];
